name: paddle39
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.9.23=he99959a_0
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h993c535_1
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - ase==3.26.0
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==25.4.0
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - cif2cell==2.1.0
      - cloudpickle==3.1.2
      - colorlog==6.9.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - cython==3.2.1
      - decorator==5.2.1
      - dgl==2.1.0
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - filelock==3.19.1
      - flatbuffers==25.9.23
      - fonttools==4.58.5
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gammagl==0.4.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h11==0.16.0
      - h5py==3.14.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - hydra-core==1.3.2
      - idna==3.10
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - jarvis-tools==2025.5.30
      - jinja2==3.1.6
      - joblib==1.5.1
      - keras==3.10.0
      - kiwisolver==1.4.7
      - latexcodec==3.0.1
      - lazy-loader==0.4
      - libclang==18.1.1
      - llvmlite==0.43.0
      - markdown==3.9
      - markdown-it-py==3.0.0
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - meshio==5.3.4
      - ml-dtypes==0.5.3
      - monty==2025.3.3
      - mpmath==1.3.0
      - multidict==6.7.0
      - namex==0.1.0
      - narwhals==2.11.0
      - networkx==3.2.1
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu11==8.9.6.50
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu11==2.19.3
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - opencv-python==4.12.0.88
      - opt-einsum==3.3.0
      - optree==0.18.0
      - packaging==25.0
      - paddlepaddle-gpu==3.1.0
      - paddlesci==1.4.0
      - palettable==3.3.3
      - panda==0.3.1
      - pandas==2.3.1
      - pgl==2.2.6
      - pillow==11.2.1
      - plotly==6.4.0
      - pluggy==1.6.0
      - ply==3.11
      - progressbar2==4.5.0
      - propcache==0.4.1
      - protobuf==6.31.1
      - psutil==7.1.3
      - pyaml==25.7.0
      - pybind11==3.0.1
      - pybtex==0.25.1
      - pycifrw==4.4.6
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyevtk==1.6.0
      - pygments==2.19.2
      - pymatgen==2024.8.9
      - pyparsing==3.2.3
      - pytest==8.4.2
      - python-dateutil==2.9.0.post0
      - python-utils==3.9.1
      - pytz==2025.2
      - pyyaml==6.0.2
      - rdkit==2025.9.1
      - requests==2.32.4
      - rich==14.0.0
      - ruamel-yaml==0.18.16
      - ruamel-yaml-clib==0.2.15
      - scikit-image==0.24.0
      - scikit-learn==1.4.2
      - scikit-optimize==0.10.2
      - scipy==1.13.1
      - seaborn==0.13.2
      - six==1.15.0
      - sniffio==1.3.1
      - spglib==2.6.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - tensorflow==2.20.0
      - tensorlayerx==0.5.8
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - tomli==2.3.0
      - toolz==1.1.0
      - torch==2.8.0
      - torch-geometric==2.6.1
      - torchdata==0.11.0
      - tqdm==4.67.1
      - triton==3.4.0
      - typing-extensions==4.14.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - uncertainties==3.2.3
      - urllib3==2.5.0
      - werkzeug==3.1.3
      - wget==3.2
      - wrapt==2.0.1
      - xmltodict==1.0.2
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /home/wangxiean/app/miniconda3/envs/paddle39
